### ISSUE TITLE
Failed to build with recent gimp git (2.9.5+) (GIMP_LAYER_MODE_HSV_COLOR_LEGACY)

### ISSUE THREAD

**Issue by JeanLucCoulon** [dtschump/gmic-community#71]
Hi,
I failed to build GMIC latest git version with latest gimp git version.

I get the following:
[...]
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp: In function ‘void get_output_layer_props(const char*, GimpLayerModeEffects&, double&, int&, int&, cimg_library::CImg<char>&)’:
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:407:33: error: ‘GIMP_LAYER_MODE_HSV_COLOR_LEGACY’ was not declared in this scope
 #define GIMP_COLOR_MODE         GIMP_LAYER_MODE_HSV_COLOR_LEGACY
[...]

There are several warning related to this before the error itself.

[ 58%] Building CXX object CMakeFiles/gmic_gimp_gtk.dir/src/gmic_gimp_gtk.cpp.o
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:394:0: warning: "GIMP_NORMAL_MODE" redefined
 #define GIMP_NORMAL_MODE        GIMP_LAYER_MODE_NORMAL
 
In file included from /usr/include/gimp-2.0/libgimp/gimp.h:36:0,
                 from /usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:50:
/usr/include/gimp-2.0/libgimp/gimptypes.h:49:0: note: this is the location of the previous definition
 #define GIMP_NORMAL_MODE        GIMP_LAYER_MODE_NORMAL_LEGACY
 
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:396:0: warning: "GIMP_BEHIND_MODE" redefined
 #define GIMP_BEHIND_MODE        GIMP_LAYER_MODE_BEHIND
 
In file included from /usr/include/gimp-2.0/libgimp/gimp.h:36:0,
                 from /usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:50:
/usr/include/gimp-2.0/libgimp/gimptypes.h:51:0: note: this is the location of the previous definition
 #define GIMP_BEHIND_MODE        GIMP_LAYER_MODE_BEHIND_LEGACY
 
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:407:0: warning: "GIMP_COLOR_MODE" redefined
 #define GIMP_COLOR_MODE         GIMP_LAYER_MODE_HSV_COLOR_LEGACY
 
In file included from /usr/include/gimp-2.0/libgimp/gimp.h:36:0,
                 from /usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:50:
/usr/include/gimp-2.0/libgimp/gimptypes.h:62:0: note: this is the location of the previous definition
 #define GIMP_COLOR_MODE         GIMP_LAYER_MODE_HSL_COLOR_LEGACY
 
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:416:0: warning: "GIMP_COLOR_ERASE_MODE" redefined
 #define GIMP_COLOR_ERASE_MODE   GIMP_LAYER_MODE_COLOR_ERASE
 
In file included from /usr/include/gimp-2.0/libgimp/gimp.h:36:0,
                 from /usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:50:
/usr/include/gimp-2.0/libgimp/gimptypes.h:71:0: note: this is the location of the previous definition
 #define GIMP_COLOR_ERASE_MODE   GIMP_LAYER_MODE_COLOR_ERASE_LEGACY
 
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp: In function ‘void get_output_layer_props(const char*, GimpLayerModeEffects&, double&, int&, int&, cimg_library::CImg<char>&)’:
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:407:33: error: ‘GIMP_LAYER_MODE_HSV_COLOR_LEGACY’ was not declared in this scope
 #define GIMP_COLOR_MODE         GIMP_LAYER_MODE_HSV_COLOR_LEGACY
                                 ^
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:424:67: note: in definition of macro ‘_get_output_layer_blendmode’
     if (!std::strncmp(S + 5,in,l) && S[5 + l]==')') { blendmode = out; is_blendmode = true; } \
                                                                   ^~~
/usr/local/src/gmic/gmic-2.0.0/src/gmic_gimp_gtk.cpp:452:39: note: in expansion of macro ‘GIMP_COLOR_MODE’
   _get_output_layer_blendmode("color",GIMP_COLOR_MODE);
                                       ^
CMakeFiles/gmic_gimp_gtk.dir/build.make:86 : la recette pour la cible « CMakeFiles/gmic_gimp_gtk.dir/src/gmic_gimp_gtk.cpp.o » a échouée

Regards

Jean-Luc

**Comment by tobybear** [comment]
As far as I know, GIMP_LAYER_MODE_HSV_COLOR_LEGACY was recently changed to GIMP_LAYER_MODE_HSL_COLOR_LEGACY in the GIMP sources, so should be an easy fix :)

**Comment by IvanDSM** [comment]
I'm unable to build G'MIC 2.0.0 or 2.0.3_pre with GIMP 2.9.4-r3 due to this bug. Using Gentoo with no overlays.
